{% set version = '0.9.6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plsvarsel
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/plsVarSel_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/plsVarSel/plsVarSel_{{ version }}.tar.gz
  sha256: 1c47f6001e792a76fccc89b33c59258b169fafd8985627d8165ffc464f7d117d

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-msqc
    - r-bdsmatrix
    - r-genalg
    - r-mvtnorm
    - r-pls
    - r-praznik
    - r-progress
  run:
    - r-base
    - r-mass
    - r-msqc
    - r-bdsmatrix
    - r-genalg
    - r-mvtnorm
    - r-pls
    - r-praznik
    - r-progress

test:
  commands:
    - $R -e "library('plsVarSel')"           # [not win]
    - "\"%R%\" -e \"library('plsVarSel')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=plsVarSel
  license: GPL-2.0-or-later
  summary: Interfaces and methods for variable selection in Partial Least Squares. The methods
    include filter methods, wrapper methods and embedded methods. Both regression and
    classification is supported.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Encoding: UTF-8
# Package: plsVarSel
# Type: Package
# Title: Variable Selection in Partial Least Squares
# Version: 0.9.6
# Date: 2020-04-03
# Author: Kristian Hovde Liland, Tahir Mehmood, Solve Sb
# Maintainer: Kristian Hovde Liland <kristian.liland@nmbu.no>
# Description: Interfaces and methods for variable selection in Partial Least Squares. The methods include filter methods, wrapper methods and embedded methods. Both regression and classification is supported.
# License: GPL (>= 2)
# Depends: pls
# Imports: grDevices, graphics, genalg, mvtnorm, bdsmatrix, MASS, progress, parallel, stats, MSQC, praznik
# Suggests: Rmpi
# RoxygenNote: 7.1.0
# NeedsCompilation: no
# Packaged: 2020-04-03 08:25:47 UTC; kristl
# Repository: CRAN
# Date/Publication: 2020-04-03 08:40:02 UTC
